apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-acc-v3
  description: Tanzu Java Web App
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=test-acc-v3'
spec:
  type: service
  lifecycle: experimental
  owner: default-team
